config/routes.rb
Hashes::Application.routes.draw do
  root to: 'notes#index', as: :notes_home

  match 'sandwich' => 'notes#sandwich', as: :notes_sandwich, via: [:get, :post]
  get 'codesample/:name' => 'notes#code_sample', as: :notes_code_sample

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def self.code_samples
    @@code_samples
  end

  CREATE_SYMBOL_HASH = 'hsh = { name: "Wallace", dob: Date.new(1955,2,14), lang: "British English", favourite: "Vegan Captain Kirk" }'
  CREATE_STRING_HASH = 'hsh2 = { "name" => "Wallace", "dob" => Date.new(1955,2,14), "lang" => "British English", "favourite" => "Vegan Captain Kirk" }'
  CREATE_SYMBOL_HASH_GROMIT = 'gromit = { name: "Gromit", dob: Date.new(2001,7,4) ,address: {street: "100 Main Road", town: "Wensleydale", postcode: "WCH 33Z" } }'
  CREATE_SYMBOL_HASH_WITH_DEFAULT = 'hsh = Hash.new("N/A")'

  #TODO: Move these to a Model class
  @@code_samples =
      {
          declare_empty_hash_braces: 'hsh = {}',
          declare_empty_hash_new: 'hsh = Hash.new',
          declare_with_symbols: CREATE_SYMBOL_HASH,
          declare_with_strings: CREATE_STRING_HASH,

          symbols_vs_strings:[CREATE_SYMBOL_HASH,
                              'p hsh[:name]',
                              'p hsh["name"]'
          ],
          symbols_vs_strings_advanced:[CREATE_SYMBOL_HASH, CREATE_STRING_HASH,
            'p hsh','p hsh2',
            'puts "Hash with symbols as keys"',
            'p hsh[:name]',    
            'p hsh["name"]',    
            'puts "Hash with strings as keys"',
            'p hsh2[:name]',    
            'p hsh2["name"]',    
            'hsh3 = hsh2.deep_symbolize_keys  #Provided By Active Support core extentions',
            'puts "Hash with strings as keys converted to symbols"',
            'p hsh3[:name]',    
            'p hsh3["name"]',
            'puts "Hash with strings as keys with_indifferent_access (active_support/hash_with_indifferent_access)"',
            'p hsh2.with_indifferent_access[:name]',    
            'p hsh2.with_indifferent_access["name"]'
            ],

          hash_get_value: [CREATE_SYMBOL_HASH ,'hsh[:name]'].join("\n"),
          hash_set_value: [CREATE_SYMBOL_HASH ,'hsh[:age]=42','hsh[:age]'].join("\n"),
          hash_has_key: [CREATE_SYMBOL_HASH ,'hsh.has_key? :age'].join("\n"),
      
          hash_empty: [CREATE_SYMBOL_HASH ,'hsh.empty?'].join("\n"),
          hash_length: [CREATE_SYMBOL_HASH ,'hsh.length'].join("\n"),
          hash_each: [CREATE_SYMBOL_HASH ,'results = Array.new',
              'hsh.each {|key,value| results << "#{key} refers to #{value}"}',
              'results'].join("\n"),
          hash_clear: [CREATE_SYMBOL_HASH ,'hsh.clear'].join("\n"),
          hash_delete: [CREATE_SYMBOL_HASH ,'p hsh.delete :favourite','hsh'].join("\n"),
          hash_merge: [CREATE_SYMBOL_HASH , CREATE_SYMBOL_HASH_GROMIT,  'result = hsh.merge gromit', 'p hsh', 'result'].join("\n"),
          hash_destructive_merge_with_result: [CREATE_SYMBOL_HASH , CREATE_SYMBOL_HASH_GROMIT,  'p hsh.merge! gromit', 'hsh'].join("\n"),

          hash_select: [CREATE_SYMBOL_HASH,  'result = hsh.select {|key,value| value.is_a? String }', 'p hsh', 'result'].join("\n"),
          hash_keys: [CREATE_SYMBOL_HASH_GROMIT,  'gromit.keys'].join("\n"),
          hash_values: [CREATE_SYMBOL_HASH_GROMIT,  'gromit.values'].join("\n"),
          hash_values: [CREATE_SYMBOL_HASH_GROMIT,  'gromit.values'].join("\n"),

          hash_with_default: [CREATE_SYMBOL_HASH_WITH_DEFAULT,'p hsh','p hsh[:name]','hsh[:name]="Shawn"','hsh[:name]'],
          hash_fetch: [CREATE_SYMBOL_HASH_WITH_DEFAULT,'p hsh.fetch(:name,nil)','hsh[:name]="Shawn"','hsh.fetch(:name,nil)'],

          declare_empty_hash_with_array: 'hsh = Hash[1,2,3,4,5,6,7,8]',
          declare_empty_hash_with_odd: 'hsh = Hash["one","two","three"]',
          hash_from_to_h: ['hsh = {flavour: "Strawberry"}',
                           'puts "hsh(#{hsh.class}) = ";p hsh.to_h',
                           'puts "NIL(#{nil.class}) = "; p nil.to_h',
                           'puts "ENV(#{ENV.class}) = ";p ENV.to_h'
                           ],

          hash_delete_if:  [CREATE_SYMBOL_HASH, 'p hsh', 'p hsh.delete_if{|key,value| :favourite == key}','p hsh'],

          hash_default_proc: [CREATE_SYMBOL_HASH, 'hsh.default_proc=proc {|hash,key| "\'#{key}\' is missing"}', 'hsh[:customer_since]'],
          hash_hash: [CREATE_SYMBOL_HASH, 'hsh.hash'],

          hash_to_param: [CREATE_SYMBOL_HASH, 'hsh.to_param'],
          hash_flatten: [CREATE_SYMBOL_HASH_GROMIT, 'gromit.flatten'],
          hash_slice: [CREATE_SYMBOL_HASH_GROMIT, 'gromit.slice(:name,:address)'],
          hash_rehash: ['k1 = ["a","b"]','k2 = ["c","d"]','hsh=Hash[k1 => "value1", k2 => "value2"]', 'p hsh[k1]','k1[0]="x"', 'p k1', 'p hsh[k1]','hsh.rehash','p hsh[k1]'],
          hash_invert: [CREATE_SYMBOL_HASH, 'hsh[:nickname]="Wallace"', 'p hsh.invert','hsh'],
          hash_replace: [CREATE_SYMBOL_HASH,CREATE_SYMBOL_HASH_GROMIT, 'p hsh.object_id','hsh.replace gromit','p hsh', 'p hsh.object_id'],
          hash_shift: [CREATE_SYMBOL_HASH, 'p hsh.shift','hsh'],
          hash_to_a: [CREATE_SYMBOL_HASH_GROMIT,'gromit.to_a'],
          hash_diff: [CREATE_SYMBOL_HASH, CREATE_SYMBOL_HASH_GROMIT,'p gromit.diff hsh','p hsh.diff gromit'],

          code_sample_syntax_error_demo: [CREATE_SYMBOL_HASH, 'p hsh', 'hsh.sze']
    }




  def index
  end

  def ancestry(object)
    ancs = lambda { |kl, ancs|
      return kl.superclass.nil? ? [kl] : ancs.call(kl.superclass, ancs) << kl
    }
    ancs.call(object.class, ancs)
  end

  def sandwich
    @formvalues = params[:sandwich_form]
    @ancestry = ancestry(@formvalues)

    # Pre-populate the form values to save time in demo
    unless @formvalues.nil?
      defaults = @formvalues.to_h
    else
      defaults = {sandwich: 'Meatless Mike'}
    end

    @sandwiches = [
        "Al Bundy",
        "Backstabber",
        "Barry B.",
        "Barry Z.",
        "Bella",
        "Blind Date",
        "Brutus",
        "Captain Kirk",
        "Change",
        "Chipper's Fave",
        "Curtis",
        "Doomsday",
        "Elvis Kieth",
        "Everett Middle School",
        "Fat Bastard",
        "Forty!??",
        "Going Home For Thanksgiving",
        "Green Goblin",
        "Handsome Owl",
        "Heath Ledger",
        "Hollywood's SF Cheesesteak",
        "Holy Name Panthers",
        "Hot Momma Huda",
        "Jaymee Sirewich",
        "Jessica Rabbit",
        "Jim Rome",
        "Kryptonite",
        "Lex Luthor",
        "Lincecum",
        "Lizzy's Lips",
        "Love Triangle",
        "Matt Cain",
        "Mayoose's CA-BLT",
        "Meatless Mike",
        "Menage A Trois",
        "Nacho Boy",
        "Nacho Girl",
        "Pastrami-Charmed Life",
        "Paul Reubens",
        "Pee Wee",
        "Peg Bundy",
        "Pilgrim",
        "Pizzle",
        "Purple B's Veggie CA-BLT",
        "Sabrina's Smile",
        "Sanchez College Prep",
        "Say Hey",
        "SF Giants",
        "Sometimes I'm a Vegetarian",
        "Spiffy Tiffy",
        "Stephan Jenkins",
        "Stupid Eggplant Sandwich",
        "Super Mario",
        "The Count of Monte Chase-o",
        "The Damon Bruce",
        "The Gramps",
        "The Joker",
        "Tom Brady",
        "Tony Soprano",
        "Vegan Brutus",
        "Vegan Bud Bundy",
        "Vegan Captain Kirk",
        "Vegan Everett Middle School",
        "Vegan Gramps",
        "Vegan Green Goblin",
        "Vegan Handsome Owl",
        "Vegan Meatless Mike",
        "Vegan Pilgrim",
        "Vegan Reuben",
        "Vegan Sabrina's Smile",
        "Vegan Sometimes I'm a Vegan",
        "Vegan Strawberry Girl",
        "Vegan Tom Brady",
        "Vegan Womanizer",
        "Vegan XXXtina",
        "Vegan Your Favorite Sesame Street Character",
        "Wario",
        "We're JUST Friends",
        "Womanizer",
        "XXXtina",
        "Your Favorite Sesame Street Character",
    ]

    @sandwich = SandwichForm.new (defaults)
  end

  def beautify_code_sample(sample)
    sample #sample.gsub(/{/,"{\n ").gsub(/}/,"\n}")
  end

  def code_sample
    @code_sample_options = @@code_samples.keys.map{|key| [key, "codesample/" + key.to_s]}
    @sample_name = params.require('name')
    @sample_path = "codesample/" + @sample_name.to_s
    @code_sample = @@code_samples.fetch @sample_name.to_sym, nil
    if @code_sample.nil?
      redirect_to notes_home_path, :alert => "Code Sample Missing"
    else
      @code_sample = @code_sample.join("\n") if @code_sample.is_a? Array

      eval_current_code_sample

      @code_sample = beautify_code_sample(@code_sample)
    end
  end


  def run_code_sample sample
    #Kernel.eval(sample)

    sandbox = Shikashi::Sandbox.new
    privileges = Shikashi::Privileges.new
    privileges.allow_all
    sandbox.run(privileges, sample)

  end

  def eval_current_code_sample
    std_output = StringIO.new;
    std_error = StringIO.new;

    begin
      $stdout = std_output
      $stderr = std_error
      @code_result = run_code_sample @code_sample
    rescue SyntaxError => se
      @syntax_error = se
    rescue NameError => ne
      @syntax_error = ne
    rescue TypeError => te
      @syntax_error = te
    rescue ArgumentError => ae
      @syntax_error = ae
    ensure
      $stdout = STDOUT
      $stderr = STDERR
    end

    @std_error = std_error.string
    @std_output = std_output.string

  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/code_sample.html.erb
<% content_for :title do %>Code Sample:
    <%= @sample_name %>
<% end %>
<ol class="breadcrumb">
  <li><%= link_to 'Hash Notes', notes_home_path %></li>
  <li><%= link_to 'More', notes_home_path(:anchor => 'hashAdvanced') %></li>
  <li><%= link_to 'Basic Use', notes_home_path(:anchor => 'hashBasics') %></li>
  <li class="active"><%= yield(:title) %></li>
</ol>
<form class="form-inline" novalidate="novalidate" role="form">
  <label>Select a sample:</label>
  <%= select_tag "code_sample", options_for_select(@code_sample_options, @sample_path),
                 {
                         class: 'form-control',
                         style: 'width: 100%',
                         onchange: "document.location.href='/' + this.value"
                 } %>
</form>
<hr>
<h1 id="sandwich" class="page-header">Code Sample:
  <%= @sample_name %></h1>
<%= raw CodeRay.scan(@code_sample, :ruby).div(:line_numbers => :table) %>
<hr/>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#codeResult">
          Show Results
        </a>
      </h4>
    </div>
    <div id="codeResult" class="panel-collapse collapse">
      <div class="panel-body">
        <% unless @code_result.nil? %>
            <h4><%= @code_result.class %></h4>
            <%= raw CodeRay.scan(@code_result, :ruby).div(:break_lines => true) %>
        <% else %>
        <PRE>nil</PRE>
        <% end %>
        <% unless @std_output.to_s == '' %>
            <div class="alert alert-info">
              <h4>STDOUT</h4>
              <PRE><%= h @std_output %></PRE>
            </div>
        <% end %>
        <% unless @std_error.to_s == '' %>
            <div class="alert alert-warning">
              <h4>STDERR</h4>
              <PRE><%= h @std_error %></PRE>
            </div>
        <% end %>
        <% unless @syntax_error.nil? %>
            <div class="alert alert-danger">
              <h4>Syntax Error</h4>
              <PRE><%= h @syntax_error %></PRE>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<% content_for :title do %>Hashes in Ruby
<% end %>
<ol class="breadcrumb">
  <li class="active">Hash Notes</li>
</ol>
<h1 id="hashes" class="page-header"><%= yield(:title) %></h1>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#hashIntro">
          Introduction - 1 minute
        </a>
      </h4>
    </div>
    <div id="hashIntro" class="panel-collapse collapse">
      <div class="panel-body">
        <ul>
          <li>Everything in Ruby is an object and Hash is a built in ruby object class
          </li>
          <li>Hashes are collections of unique object keys and their associated object values</li>
          <li>If you’re coming in from other programming languages, hashes are similar to types like
            <ul>
              <li><a href="http://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html">Java HashMap</a></li>
              <li><a href="http://msdn.microsoft.com/en-us/library/xfhwa508(v=vs.110).aspx">.NET Dictionary</a></li>
              <li><a href="http://php.net/manual/en/language.types.array.php">PHP Associative Array</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#hashWhyCare">
          Why Should I Care? - 2 minutes
        </a>
      </h4>
    </div>
    <div id="hashWhyCare" class="panel-collapse collapse">
      <div class="panel-body">
        <ul>
          <li><%= link_to "Rails Form Parameters", notes_sandwich_path %></li>
          <li>JSON
            <a href="http://json.org/example.html">http://json.org/example.html</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#hashBasics">
          Basic Usage of Hash - 7 minutes
        </a>
      </h4>
    </div>
    <div id="hashBasics" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Getting Started - Code Samples</h4>
        <ul>
          <li><b><a href="/codesample/declare_with_symbols">Declare with symbols as keys</a></b></li>
          <li><b><a href="/codesample/declare_with_strings">Declare with strings as keys</a></b></li>
          <li><b><a href="/codesample/hash_get_value">hsh.[] - Get value for key</a></b></li>
          <li><b><a href="/codesample/symbols_vs_strings">Symbols or Strings as keys</a></b></li>
        </ul>
        <h4>Creating Hash Objects - Code Samples</h4>
        <ul>
          <li><a href="/codesample/declare_empty_hash_braces">Empty Hash with braces</a></li>
          <li><a href="/codesample/declare_empty_hash_new">Empty Hash with Hash.new</a></li>
        </ul>
        <h4>Commonly Used Methods - Code Samples</h4>
        <ul>
          <li><a href="/codesample/hash_set_value">hsh.[]= - Set value for key</a></li>
          <li><a href="/codesample/hash_has_key">hsh.has_key? - Check for key existence</a></li>
          <li><a href="/codesample/hash_empty">hsh.empty? - Contains something or not</a></li>
          <li><b><a href="/codesample/hash_each">hsh.each - do block for each key,value</a></b></li>
          <li><a href="/codesample/hash_keys">hsh.keys - Array of keys</a></li>
          <li><a href="/codesample/hash_values">hsh.values - Array of values</a></li>
          <li><a href="/codesample/hash_length">hsh.length - How many</a></li>
          <li><b><a href="/codesample/hash_select">hsh.select - New hash with block passed pairs</a></b></li>
          <li><a href="/codesample/hash_clear">hsh.clear - Remove all entries</a></li>
          <li><a href="/codesample/hash_delete">hsh.delete(key) - Remove specified entry</a></li>
          <li><b><a href="/codesample/hash_merge">hsh.merge - Blend with another hash</a></b></li>
        </ul>
        <h4>Rails ActiveSupport Methods</h4>
        <ul>
          <li><a href="/codesample/symbols_vs_strings_advanced">symbolize_keys</a></li>
          <li><b><a href="/codesample/hash_to_param">to_param</a></b></li>
          <li><a href="/codesample/hash_slice">slice</a></li>
          <li><a href="/codesample/hash_diff">diff</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#hashAdvanced">
          More Hash - 5 minutes
        </a>
      </h4>
    </div>
    <div id="hashAdvanced" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>More Ways to Create Hash Objects - Code Samples</h4>
        <ul>
          <li><a href="/codesample/declare_empty_hash_with_array">Hash[] from array</a></li>
          <li><a href="/codesample/hash_from_to_h">to_h</a></li>
        </ul>
        <h4>More Code Samples</h4>
        <ul>
          <li><b><a href="/codesample/hash_with_default">Hash.new(0) - Specify default value</a></b></li>
          <li><a href="/codesample/hash_fetch">hsh.fetch - When you want control over defaults</a></li>
          <li><b><a href="/codesample/symbols_vs_strings_advanced">More Symbols or Strings as keys</a></b></li>
          <li><b><a href="/codesample/hash_delete_if">Removing items via Enumeration</a></b></li>
          <li><b><a href="/codesample/hash_default_proc">Generate default values with a Proc</a></b>
            <ul><li><a href="http://endofline.wordpress.com/2010/12/24/hash-tricks/">http://endofline.wordpress.com/2010/12/24/hash-tricks/</a></li></ul>
          </li>
          <li><a href="/codesample/hash_hash">hsh.hash - Not a Hash!</a></li>
          <!-- 
          <li>hsh == b Is this hash the same as another hash</li>
          <li>hsh.assoc Find a key value pair or nil</li>
          <li>hsh.compare_by_identity Use object ids instead of equality for lookups</li>
          <li>hsh.default Returns the default value that would be used</li>
          <li>hsh.default= Sets the default value</li>
          <li>hsh.default_proc Returns the proc to be executed on failing lookup</li>
          <li>hsh.default_proc= Assigns a  default proc</li>
          <li>hsh.default_proc= proc do |hash,key| "default for #{key}" end</li>
          <li>Cool uses of default_proc</li>
          <li>http://endofline.wordpress.com/2010/12/24/hash-tricks/</li>
          <li>hsh.each_key</li>
          <li>hsh.each_pair</li>
          <li>hsh.each_value</li>
          <li>hsh.eql?</li>
           -->
          <li><a href="/codesample/hash_flatten">hsh.flatten - Keys and values into a unidimensional array</a></li>
          <!-- 
          <li>hsh.has_value?</li>
          <li>hsh.hash</li>
 -->
          <li><a href="/codesample/hash_has_key">hsh.include? hsh.key? hsh.member? hsh.has_key?</a></li>
          <!--       
          <li>hsh.inspect</li>
          <li>hsh.keep_if opposite of delete_if</li>
          <li>key - Looks up the first occurrence of the value</li>
          <li>merge! - Destructive Merge</li>
          <li>rassoc - Find key value pair by value</li>
          <li>reject - new hash without failing pairs (opposite of select)</li>
          <li>reject! - delete_if</li>
          <li>select! - keep_if</li>
          <li>size - same as length</li>
          <li>store same as []=</li>
 -->
          <li><a href="/codesample/hash_invert">hsh.invert - Swaps keys and values</a></li>
          <li><a href="/codesample/hash_replace">hsh.replace - Replace Contents</a></li>
          <li><a href="/codesample/hash_shift">hsh.shift - Pops first item off of hash</a></li>
          <li><a href="/codesample/hash_rehash">hsh.rehash - If using unfrozen objects as keys</a></li>
          <li><a href="/codesample/hash_to_a">hsh.to_a - Array of pairs</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#hashResources">
          Resources - 1 minute
        </a>
      </h4>
    </div>
    <div id="hashResources" class="panel-collapse collapse">
      <div class="panel-body">
        <ul>
          <li>Ruby Core Docs
            <a href="http://www.ruby-doc.org/core-2.1.0/Hash.html">http://www.ruby-doc.org/core-2.1.0/Hash.html</a>
          </li>
          <li>Rails ActiveSupport Methods
            <a href="http://api.rubyonrails.org/classes/Hash.html">http://api.rubyonrails.org/classes/Hash.html</a>
          </li>
          <li>Related Classes
            <ul>
              <li>Array
                <a href="http://www.ruby-doc.org/core-2.1.0/Array.html">http://www.ruby-doc.org/core-2.1.0/Array.html</a>
              </li>
              <li>Enumerable
                <a href="http://www.ruby-doc.org/core-2.1.0/Enumerable.html">http://www.ruby-doc.org/core-2.1.0/Enumerable.html</a>
              </li>
              <li>Enumerator
                <a href="http://www.ruby-doc.org/core-2.1.0/Enumerator.html">http://www.ruby-doc.org/core-2.1.0/Enumerator.html</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>


<script>
  <!--
  if (window.location.hash) {
      $(window.location.hash).addClass("in");
  }
  -->
</script>

app/views/notes/sandwich.html.erb
<% content_for :title do %>Sandwich Form
<% end %>

<ol class="breadcrumb">
  <li><%= link_to 'Hash Notes', notes_home_path %></li>
  <li><%= link_to 'Why Care?', notes_home_path(:anchor => 'hashWhyCare') %></li>
  <li class="active">Sandwich Demo</li>
</ol>

<h1 id="sandwich" class="page-header">Sandwich Please!</h1>
<% unless @formvalues.nil? %>
    <div class="alert alert-success">
      <a href="http://ilikeikesplace.com/"><b>Hungry?</b>
        Check out Ike's Place for these real-life sandwiches!</a>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Yum! This is what I got:</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-8">
            <PRE style="min-height: 250px"><%= JSON.pretty_generate(@formvalues.to_h) %></PRE>
          </div>
          <div class="col-md-4">
            <img class="img-responsive" style="max-height: 250px" src="http://www.memecreator.org/static/images/memes/2320262.jpg"/>
          </div>
        </div>

        <div class="well">
          <% unless @ancestry.nil? %>
              <% @ancestry.each_with_index do |kl, index| %>
                  <%= (index > 0) ? '<' : '' %>
                  <span <%= raw Hash == kl ? 'class="superbold"' : '' %>>
                  <%= kl.to_s %>
                  </span>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <hr/>
<% end %>
<%= bootstrap_form_for(@sandwich, url: notes_sandwich_path) do |f| %>
    <%= f.text_field :name %>
    <%= f.select(:sandwich, @sandwiches) %>
    <%= f.select(:options, [['Mustard', 'mustard'],
                            ['Cheese', 'cheese'],
                            ['Lettuce', 'lettuce'],
                            ['Salt', 'salt'],
                            ['Pepper', 'pepper'],
                            ['Tomato', 'tomato']],
                 {include_hidden: false},
                 {multiple: true, size: 6}
        ) %>
    <%= f.submit 'Place Order' %>
<% end %>
<hr/>