config/routes.rb
Hashes::Application.routes.draw do
  root to: 'notes#index', as: :notes_home

  match 'sandwich' => 'notes#sandwich', as: :notes_sandwich, via: [:get, :post]
  get 'codesample/:name' => 'notes#code_sample', as: :notes_code_sample

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= content_for?(:title) ? yield(:title) : 'Home' %> | Stujo : Demos</title>

  <!-- Bootstrap -->
  <%= stylesheet_link_tag    "application", media: "all" %>


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "GA Demos", notes_home_path, class: "navbar-brand" %>
    </div>
  </div>
</div>

<div class="container">
  <%= render 'layouts/messages' %>

  <%= yield %>
</div><!-- /.container -->
</body>
</html>